/** Native Windows window that installs the update and reopens the app. */
export function windowsUpdateWindowScript(): string {
  return [
    '$ErrorActionPreference = "Stop"',
    '$config = Get-Content -LiteralPath $args[0] -Raw -Encoding UTF8 | ConvertFrom-Json',
    '',
    'function Find-MockForgeExe {',
    '  $roots = @(',
    '    "HKCU:\\Software\\Microsoft\\Windows\\CurrentVersion\\Uninstall",',
    '    "HKLM:\\Software\\Microsoft\\Windows\\CurrentVersion\\Uninstall",',
    '    "HKLM:\\Software\\WOW6432Node\\Microsoft\\Windows\\CurrentVersion\\Uninstall"',
    '  )',
    '  foreach ($root in $roots) {',
    '    if (-not (Test-Path -LiteralPath $root)) { continue }',
    '    foreach ($key in @(Get-ChildItem -LiteralPath $root -ErrorAction SilentlyContinue)) {',
    '      $item = Get-ItemProperty -LiteralPath $key.PSPath -ErrorAction SilentlyContinue',
    '      if ($item.DisplayName -ne "MockForge") { continue }',
    '      if ($item.InstallLocation) {',
    '        $exe = Join-Path $item.InstallLocation "MockForge.exe"',
    '        if (Test-Path -LiteralPath $exe) { return $exe }',
    '      }',
    '      if ($item.DisplayIcon) {',
    '        $icon = ($item.DisplayIcon -replace ",.*$", "").Trim(\'"\')',
    '        if ($icon -and (Test-Path -LiteralPath $icon)) { return $icon }',
    '      }',
    '    }',
    '  }',
    '  $fallbacks = @(',
    '    (Join-Path $env:LOCALAPPDATA "Programs\\MockForge\\MockForge.exe"),',
    '    (Join-Path $env:ProgramFiles "MockForge\\MockForge.exe")',
    '  )',
    '  if (${env:ProgramFiles(x86)}) {',
    '    $fallbacks += Join-Path ${env:ProgramFiles(x86)} "MockForge\\MockForge.exe"',
    '  }',
    '  foreach ($path in $fallbacks) {',
    '    if ($path -and (Test-Path -LiteralPath $path)) { return $path }',
    '  }',
    '  return $null',
    '}',
    '',
    'function Start-MockForge {',
    '  $found = Find-MockForgeExe',
    '  if ($found) {',
    '    Start-Process -FilePath $found | Out-Null',
    '    return $true',
    '  }',
    '  foreach ($candidate in @($config.relaunchPaths)) {',
    '    if ($candidate -and (Test-Path -LiteralPath $candidate)) {',
    '      Start-Process -FilePath $candidate | Out-Null',
    '      return $true',
    '    }',
    '  }',
    '  return $false',
    '}',
    '',
    'Add-Type -AssemblyName System.Windows.Forms',
    'Add-Type -AssemblyName System.Drawing',
    '[System.Windows.Forms.Application]::EnableVisualStyles()',
    '',
    '$form = New-Object System.Windows.Forms.Form',
    '$form.Text = $config.title',
    '$form.FormBorderStyle = [System.Windows.Forms.FormBorderStyle]::FixedDialog',
    '$form.StartPosition = [System.Windows.Forms.FormStartPosition]::CenterScreen',
    '$form.ClientSize = New-Object System.Drawing.Size(420, 118)',
    '$form.MaximizeBox = $false',
    '$form.MinimizeBox = $false',
    '$form.ControlBox = $false',
    '$form.TopMost = $true',
    '$form.ShowInTaskbar = $true',
    '$form.Font = New-Object System.Drawing.Font("Segoe UI", 10)',
    '',
    '$label = New-Object System.Windows.Forms.Label',
    '$label.Text = $config.closing',
    '$label.AutoSize = $false',
    '$label.Location = New-Object System.Drawing.Point(20, 16)',
    '$label.Size = New-Object System.Drawing.Size(380, 40)',
    '',
    '$bar = New-Object System.Windows.Forms.ProgressBar',
    '$bar.Location = New-Object System.Drawing.Point(20, 68)',
    '$bar.Size = New-Object System.Drawing.Size(380, 22)',
    '$bar.Minimum = 0',
    '$bar.Maximum = 100',
    '$bar.Value = 20',
    '$bar.Style = [System.Windows.Forms.ProgressBarStyle]::Continuous',
    '',
    '$form.Controls.Add($label)',
    '$form.Controls.Add($bar)',
    '',
    '$retry = New-Object System.Windows.Forms.Button',
    '$retry.Text = $config.retry',
    '$retry.Location = New-Object System.Drawing.Point(20, 108)',
    '$retry.Size = New-Object System.Drawing.Size(180, 28)',
    '$retry.Visible = $false',
    '$close = New-Object System.Windows.Forms.Button',
    '$close.Text = $config.close',
    '$close.Location = New-Object System.Drawing.Point(220, 108)',
    '$close.Size = New-Object System.Drawing.Size(180, 28)',
    '$close.Visible = $false',
    '$form.Controls.Add($retry)',
    '$form.Controls.Add($close)',
    '',
    'function Show-UpdateFailed {',
    '  try { Start-MockForge | Out-Null } catch {}',
    '  $label.Text = $config.failed',
    '  $bar.Style = [System.Windows.Forms.ProgressBarStyle]::Continuous',
    '  $bar.Value = 100',
    '  $form.ClientSize = New-Object System.Drawing.Size(420, 156)',
    '  $retry.Visible = $true',
    '  $close.Visible = $true',
    '  $form.ControlBox = $true',
    '  $script:phase = "failed"',
    '  $timer.Stop()',
    '}',
    '',
    '$script:phase = "wait"',
    '$script:ticks = 0',
    '$script:installer = $null',
    '$script:elevated = $false',
    '',
    '$timer = New-Object System.Windows.Forms.Timer',
    '$timer.Interval = 200',
    '$timer.Add_Tick({',
    '  try {',
    '    if ($script:phase -eq "wait") {',
    '      if (Get-Process -Id $config.pid -ErrorAction SilentlyContinue) { return }',
    '      Get-Process -Name "MockForge" -ErrorAction SilentlyContinue | Stop-Process -Force -ErrorAction SilentlyContinue',
    '      $script:phase = "settle"',
    '      $script:ticks = 0',
    '      return',
    '    }',
    '    if ($script:phase -eq "settle") {',
    '      $script:ticks++',
    '      if ($script:ticks -lt 4) { return }',
    '      $label.Text = $config.installing',
    '      $bar.Style = [System.Windows.Forms.ProgressBarStyle]::Marquee',
    '      $bar.MarqueeAnimationSpeed = 30',
    '      $script:phase = "install"',
    '      $script:installer = Start-Process -FilePath $config.setupPath -ArgumentList "/S" -PassThru',
    '      return',
    '    }',
    '    if ($script:phase -eq "install") {',
    '      if ($script:installer -and -not $script:installer.HasExited) { return }',
    '      $code = 0',
    '      if ($script:installer -and $null -ne $script:installer.ExitCode) { $code = $script:installer.ExitCode }',
    '      if ($code -ne 0 -and -not $script:elevated) {',
    '        $script:elevated = $true',
    '        $script:installer = Start-Process -FilePath $config.setupPath -ArgumentList "/S" -Verb RunAs -PassThru',
    '        return',
    '      }',
    '      $label.Text = $config.opening',
    '      $bar.Style = [System.Windows.Forms.ProgressBarStyle]::Continuous',
    '      $bar.Value = 100',
    '      $script:phase = "done"',
    '      if ($code -eq 0 -and (Start-MockForge)) {',
    '        $timer.Stop()',
    '        $form.Close()',
    '        return',
    '      }',
    '      Show-UpdateFailed',
    '    }',
    '  } catch {',
    '    Show-UpdateFailed',
    '  }',
    '})',
    '',
    '$retry.Add_Click({',
    '  try {',
    '    Get-Process -Name "MockForge" -ErrorAction SilentlyContinue | Stop-Process -Force -ErrorAction SilentlyContinue',
    '    $retry.Visible = $false',
    '    $close.Visible = $false',
    '    $form.ControlBox = $false',
    '    $form.ClientSize = New-Object System.Drawing.Size(420, 118)',
    '    $label.Text = $config.installing',
    '    $bar.Style = [System.Windows.Forms.ProgressBarStyle]::Marquee',
    '    $bar.MarqueeAnimationSpeed = 30',
    '    $script:elevated = $false',
    '    $script:installer = $null',
    '    $script:phase = "settle"',
    '    $script:ticks = 0',
    '    if (-not $timer.Enabled) { $timer.Start() }',
    '  } catch {',
    '    Show-UpdateFailed',
    '  }',
    '})',
    '$close.Add_Click({ $form.Close() })',
    '',
    '$form.Add_Shown({ $timer.Start() })',
    '[System.Windows.Forms.Application]::Run($form)',
    '',
  ].join('\r\n');
}

/** Native macOS window that stays up while the upgrade script replaces the app. */
export function macUpdateWindowScript(): string {
  return [
    'use framework "Foundation"',
    'use framework "AppKit"',
    'use scripting additions',
    '',
    'on run argv',
    '  set workerPid to item 1 of argv',
    '  set statusPath to item 2 of argv',
    '  set scriptPath to item 3 of argv',
    '  set titleText to item 4 of argv',
    '  set closingText to item 5 of argv',
    '  set installingText to item 6 of argv',
    '  set openingText to item 7 of argv',
    '  set failedText to item 8 of argv',
    '  set retryText to item 9 of argv',
    '  set closeText to item 10 of argv',
    '',
    '  set nsApp to current application\'s NSApplication\'s sharedApplication()',
    '  nsApp\'s setActivationPolicy:(current application\'s NSApplicationActivationPolicyRegular)',
    '',
    '  set theWindow to current application\'s NSWindow\'s alloc()\'s initWithContentRect:{{0, 0}, {440, 132}} styleMask:1 backing:2 defer:false',
    '  theWindow\'s setTitle:titleText',
    '  theWindow\'s setLevel:3',
    '  theWindow\'s setReleasedWhenClosed:false',
    '',
    '  set label to current application\'s NSTextField\'s labelWithString:closingText',
    '  label\'s setFrame:{{24, 72}, {392, 36}}',
    '  label\'s setFont:(current application\'s NSFont\'s systemFontOfSize:15)',
    '  theWindow\'s contentView()\'s addSubview:label',
    '',
    '  set bar to current application\'s NSProgressIndicator\'s alloc()\'s initWithFrame:{{24, 36}, {392, 18}}',
    '  bar\'s setIndeterminate:false',
    '  bar\'s setMinValue:0',
    '  bar\'s setMaxValue:100',
    '  bar\'s setDoubleValue:20',
    '  theWindow\'s contentView()\'s addSubview:bar',
    '',
    '  theWindow\'s |center|()',
    '  theWindow\'s makeKeyAndOrderFront:(missing value)',
    '  nsApp\'s activateIgnoringOtherApps:true',
    '',
    '  set lastStatus to ""',
    '  repeat',
    '    set raw to readStatus(statusPath)',
    '    if raw is not lastStatus and raw is not "" then',
    '      set lastStatus to raw',
    '      if raw is "installing" then',
    '        label\'s setStringValue:installingText',
    '        bar\'s setIndeterminate:true',
    '        bar\'s startAnimation:(missing value)',
    '      else if raw is "opening" then',
    '        label\'s setStringValue:openingText',
    '        bar\'s setIndeterminate:false',
    '        bar\'s setDoubleValue:90',
    '      else if raw is "closing" then',
    '        label\'s setStringValue:closingText',
    '        bar\'s setIndeterminate:false',
    '        bar\'s setDoubleValue:20',
    '      end if',
    '    end if',
    '    if raw is "done" then exit repeat',
    '    if raw is "opening" and workerIsGone(workerPid) then exit repeat',
    '    if raw is "failed" or workerIsGone(workerPid) then',
    '      set choice to askRetry(failedText, retryText, closeText)',
    '      if choice is "close" then exit repeat',
    '      set workerPid to relaunchWorker(scriptPath, statusPath)',
    '      set lastStatus to ""',
    '      label\'s setStringValue:installingText',
    '      bar\'s setIndeterminate:true',
    '      bar\'s startAnimation:(missing value)',
    '    end if',
    '    current application\'s NSRunLoop\'s currentRunLoop()\'s runMode:(current application\'s NSDefaultRunLoopMode) beforeDate:(current application\'s NSDate\'s dateWithTimeIntervalSinceNow:0.2)',
    '  end repeat',
    'end run',
    '',
    'on readStatus(statusPath)',
    '  set contents to current application\'s NSString\'s stringWithContentsOfFile:statusPath encoding:4 |error|:(missing value)',
    '  if contents is missing value then return ""',
    '  return contents as text',
    'end readStatus',
    '',
    'on workerIsGone(workerPid)',
    '  try',
    '    do shell script "kill -0 " & workerPid',
    '    return false',
    '  on error',
    '    return true',
    '  end try',
    'end workerIsGone',
    '',
    'on askRetry(failedText, retryText, closeText)',
    '  set alert to current application\'s NSAlert\'s alloc()\'s init()',
    '  alert\'s setMessageText:failedText',
    '  alert\'s addButtonWithTitle:retryText',
    '  alert\'s addButtonWithTitle:closeText',
    '  set response to alert\'s runModal()',
    '  if (response as integer) is 1000 then return "retry"',
    '  return "close"',
    'end askRetry',
    '',
    'on relaunchWorker(scriptPath, statusPath)',
    '  try',
    '    do shell script "killall MockForge >/dev/null 2>&1 || true"',
    '  end try',
    '  do shell script "printf \'%s\' installing > " & quoted form of statusPath',
    '  set newPid to do shell script "/bin/bash " & quoted form of scriptPath & " >/dev/null 2>&1 & echo $!"',
    '  return paragraph 1 of newPid',
    'end relaunchWorker',
    '',
  ].join('\n');
}
